### ISSUE TITLE
Injection of tagged strings seems to not work with `` injection

### ISSUE THREAD

**Issue by bimargulies** [pedgeio/inject-go#2]
As demonstrated by snippets below, I can't seem to get a string value to inject via `` annotations.
The injection of the FlagsContainer works, but not of the individual flags.

```
type PickupFlags struct {
	// Note that injected fields have to be public, which is ugly.
	Flag1 string `inject:"flags_f1"`
	Flag2 string `inject:"flags_f2"`
	AllFlags FlagsContainer `inject:"flags"`
}
```

Combined with:

```
module := inject.NewModule()
	flagsContainer := FlagsContainer{Flags: flags}
	module.Bind((&FlagsContainer{})).ToSingleton(&flagsContainer)

	// Install all the flags as named strings.
	for flagName := range flags {
		flagValue := flags[flagName]
		module.BindTaggedString("flags_" + flagName).ToSingleton(flagValue)
	}
```

**Comment by peter-edge** [comment]
You're not using `PickupFlags` in that example. Can you give me something I can use to reproduce this?

Fields always have to be public, this is the same in all Golang DI libraries that use reflection and tags.

**Comment by bimargulies** [comment]
I will happily make you a test case, but first I want to ask a perhaps silly question.

Do I need to explicitly use Populate in order to get `` population? If so, that explains my problems. If not, I'll make you a self-contained test case.

**Comment by bimargulies-google** [comment]
I got what I needed by using ToTaggedConstructor if the constructor has an anonymous struct with `inject` tags as a parameter. Does this mean that 'Tagged' on the 'to' side means 'do `inject` injection`? I'd be happy to make a PR with some additional doc for slow thinkers like myself to clarify this and provide an example.
